export const SUPPORT_REPORT_SOCKET_EVENTS = {
    listeners: {
        NEW_BUG_EVENT: 'SOCKET_NEW_BUG_EVENT',
        UPDATED_BUG_EVENT: 'SOCKET_UPDATED_BUG_EVENT',
        DELETED_BUG_EVENT: 'SOCKET_DELETED_BUG_EVENT',
        COMMENT_ADDED_BUG_EVENT: 'SOCKET_COMMENT_ADDED_BUG_EVENT',
        STATUS_CHANGED_BUG_EVENT: 'SOCKET_STATUS_CHANGED_BUG_EVENT',
        CLOSED_BUG_EVENT: 'SOCKET_STATUS_CLOSED_BUG_EVENT',
        HISTORY_ADDED_BUG_EVENT: 'SOCKET_HISTORY_ADDED_BUG_EVENT',
        IMAGE_ADDED_BUG_EVENT: 'SOCKET_IMAGE_ADDED_BUG_EVENT',

    }
}